name: CI - DEV

on:
  push:
    branches:
      - develop

jobs:
  train-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install databricks-cli databricks-sdk

      - name: Run job in Databricks DEV
        run: |
          databricks bundle validate --target dev
          databricks bundle deploy --target dev
          databricks bundle run training_job --target dev
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
